Repository Team-PATCH/Harmony-Android, pull requests merged in 2025-05, with the labels that each got.

#146 추억저장소
  app/build.gradle.kts
  app/src/main/java/com/teampatch/harmony/MainApp.kt
  app/src/main/java/com/teampatch/harmony/MainNavHost.kt
  core/designsystem/src/main/java/com/teampatch/core/designsystem/component/MemoryInfoView.kt
  core/designsystem/src/main/java/com/teampatch/core/designsystem/component/TempMemoryCard.kt
  core/designsystem/src/main/res/drawable/btn_search.xml
  feature/memorystorage-detail/.gitignore
  feature/memorystorage-detail/build.gradle.kts
  feature/memorystorage-detail/src/main/AndroidManifest.xml
  feature/memorystorage-detail/src/main/java/com/teampatch/memorystorage/feature/detail/MemoryStorageDetailEvent.kt
  feature/memorystorage-detail/src/main/java/com/teampatch/memorystorage/feature/detail/MemoryStorageDetailNavigation.kt
  feature/memorystorage-detail/src/main/java/com/teampatch/memorystorage/feature/detail/MemoryStorageDetailScreen.kt
  feature/memorystorage-detail/src/main/java/com/teampatch/memorystorage/feature/detail/MemoryStorageDetailUiState.kt
  feature/memorystorage-detail/src/main/java/com/teampatch/memorystorage/feature/detail/MemoryStorageDetailViewModel.kt
  feature/memorystorage-detail/src/main/res/values/strings.xml
  feature/memorystorage/.gitignore
  feature/memorystorage/build.gradle.kts
  feature/memorystorage/src/main/AndroidManifest.xml
  feature/memorystorage/src/main/java/com/teampatch/feature/memorystorage/MemoryStorageEvent.kt
  feature/memorystorage/src/main/java/com/teampatch/feature/memorystorage/MemoryStorageNavigation.kt
  feature/memorystorage/src/main/java/com/teampatch/feature/memorystorage/MemoryStorageScreen.kt
  feature/memorystorage/src/main/java/com/teampatch/feature/memorystorage/MemoryStorageUiState.kt
  feature/memorystorage/src/main/java/com/teampatch/feature/memorystorage/MemoryStorageViewModel.kt
  feature/memorystorage/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: Feature

#149 DailyManage Module 삭제(안쓰는 모듈)
  feature/daily-manage/src/main/java/com/teampatch/daily/manage/DailyManageScreen.kt
Labels: Bug, Refactor

#147 서버에 의존하고 있는 질문 기능들을 로컬 db에 의존하도록 수정하였습니다.
  core/data/src/main/java/com/teampatch/core/data/di/DataViewModelModule.kt
  core/data/src/main/java/com/teampatch/core/data/repository/local/LocalQuestionRepositoryImpl.kt
  core/database/src/main/java/com/harmony/core/database/HarmonyDatabase.kt
  core/database/src/main/java/com/harmony/core/database/Utils.kt
  core/database/src/main/java/com/harmony/core/database/dao/QuestionDao.kt
  core/database/src/main/java/com/harmony/core/database/di/DatabaseModule.kt
  core/database/src/main/java/com/harmony/core/database/model/QuestionCommentEntity.kt
  core/database/src/main/java/com/harmony/core/database/model/QuestionEntity.kt
  core/database/src/main/java/com/harmony/core/database/model/multimap/QuestionCommentWithUser.kt
  core/domain/src/main/java/com/teampatch/core/domain/usecase/question/GetQuestionDetailUseCase.kt
  core/domain/src/main/java/com/teampatch/core/domain/usecase/question/GetQuestionsUseCase.kt
Labels: Refactor

#148 일과화면 서버에서 로컬DB로 의존하도록 변경하였습니다.
  core/data/src/main/java/com/teampatch/core/data/mapper/TodoMapper.kt
  core/data/src/main/java/com/teampatch/core/data/repository/TodoOfflineRepositoryImpl.kt
  core/data/src/main/java/com/teampatch/core/data/repository/local/LocalQuestionRepositoryImpl.kt
  core/database/src/main/java/com/harmony/core/database/HarmonyDatabase.kt
  core/database/src/main/java/com/harmony/core/database/Utils.kt
  core/database/src/main/java/com/harmony/core/database/dao/QuestionDao.kt
  core/database/src/main/java/com/harmony/core/database/dao/TodoDao.kt
  core/database/src/main/java/com/harmony/core/database/di/DatabaseModule.kt
  core/database/src/main/java/com/harmony/core/database/model/TodoEntity.kt
  core/database/src/main/java/com/harmony/core/database/model/preload/DataPreloadHelper.kt
  core/database/src/main/java/com/harmony/core/database/model/preload/QuestionPreloadData.kt
  core/database/src/main/java/com/harmony/core/database/model/preload/TodoPreloadData.kt
  core/domain/src/main/java/com/teampatch/core/domain/repository/TodoRepository.kt
  core/domain/src/main/java/com/teampatch/core/domain/usecase/daily/GetDailyRoutineUseCase.kt
  core/domain/src/main/java/com/teampatch/core/domain/usecase/daily/ToggleDailyRoutineStatusUseCase.kt
  core/domain/src/main/java/com/teampatch/core/domain/usecase/routine/ToggleDailyRoutineStatusUseCase.kt
  feature/daily/src/main/java/com/teampatch/harmony/DailyScreen.kt
  feature/daily/src/main/java/com/teampatch/harmony/DailyViewModel.kt
  feature/daily/src/main/java/com/teampatch/harmony/model/DailyUiState.kt
  feature/home/src/main/java/com/teampatch/feature/home/HomeViewModel.kt
Labels: Refactor

#153 Bottom Navigation의 추억저장소 버튼을 클릭하는 경우 앱에서 크래시 나는 문제를 해결하였습니다.
  app/src/main/java/com/teampatch/harmony/MainApp.kt
  app/src/main/java/com/teampatch/harmony/MainNavHost.kt
  feature/memorystorage-detail/src/main/java/com/teampatch/memorystorage/feature/detail/MemoryStorageDetailNavigation.kt
  feature/memorystorage-detail/src/main/java/com/teampatch/memorystorage/feature/detail/MemoryStorageDetailViewModel.kt
Labels: Bug

#155 refactor: 사용하지 않는 Daily 파일들 제거
  core/domain/src/main/java/com/teampatch/core/domain/fake/FakeDaily.kt
  core/domain/src/main/java/com/teampatch/core/domain/model/Daily.kt
  core/domain/src/main/java/com/teampatch/core/domain/usecase/daily/GetDailyUseCase.kt
Labels: Refactor

#159 refactor: data module의 DI를 ViewModelComponent에서 SingletonComponent로 변경
  core/data/src/main/java/com/teampatch/core/data/di/DataSingletonModule.kt
  core/data/src/main/java/com/teampatch/core/data/di/DataViewModelModule.kt
Labels: Refactor

#158 refactor: MainApp 코드 컨벤션 위배 also -> apply 로 수정하였습니다.
  app/src/main/java/com/teampatch/harmony/MainApp.kt
Labels: Refactor

#172 가족정보 화면이 정상적으로 표시되지 않는 문제 수정합니다
  core/data/src/main/java/com/teampatch/core/data/repository/local/LocalGroupManagementRepositoryImpl.kt
Labels: Bug

#174 온보딩 마지막 수정
  app/src/main/java/com/teampatch/harmony/MainNavHost.kt
  core/designsystem/src/main/java/com/teampatch/core/designsystem/component/SpeechBubble.kt
  feature/onboarding-enter/build.gradle.kts
  feature/onboarding-enter/src/main/java/com/teampatch/feature/onboarding/enter/OnboardingEnterInvitationCodeScreen.kt
  feature/onboarding-enter/src/main/java/com/teampatch/feature/onboarding/enter/OnboardingEnterNavigation.kt
  feature/onboarding-enter/src/main/java/com/teampatch/feature/onboarding/enter/OnboardingEnterProfileSettingsScreen.kt
  feature/onboarding-enter/src/main/java/com/teampatch/feature/onboarding/enter/OnboardingEnterRelationScreen.kt
  feature/onboarding-enter/src/main/java/com/teampatch/feature/onboarding/enter/OnboardingEnterSpaceScreen.kt
  feature/onboarding-enter/src/main/java/com/teampatch/feature/onboarding/enter/viewmodel/OnboardingEnterInvitationCodeViewModel.kt
  feature/onboarding-enter/src/main/java/com/teampatch/feature/onboarding/enter/viewmodel/OnboardingEnterSpaceViewModel.kt
  feature/onboarding-enter/src/main/res/values/strings.xml
  feature/onboarding-make/src/main/java/com/teampatch/feature/onboarding/make/OnboardingMakeInviteGrandParentsScreen.kt
  feature/onboarding-make/src/main/java/com/teampatch/feature/onboarding/make/OnboardingMakeNavigation.kt
  feature/onboarding-make/src/main/java/com/teampatch/feature/onboarding/make/OnboardingMakeParentsNameScreen.kt
  feature/onboarding/src/main/java/com/teampatch/feature/onboarding/login/ui/OnboardingLoginScreen.kt
  feature/onboarding/src/main/java/com/teampatch/feature/onboarding/login/ui/OnboardingPermissionNotificationScreen.kt
  feature/onboarding/src/main/java/com/teampatch/feature/onboarding/login/ui/OnboardingRoute.kt
  feature/onboarding/src/main/java/com/teampatch/feature/onboarding/login/ui/OnboardingStartSpaceScreen.kt
  feature/onboarding/src/main/java/com/teampatch/feature/onboarding/login/ui/OnboardingViewModel.kt
  feature/onboarding/src/main/res/drawable/bell.xml
  feature/onboarding/src/main/res/values/strings.xml
  gradle.properties
Labels: Refactor

#176 프로필 수정 기능이 정상적으로 작동하지 않는 문제를 해결합니다.
  core/data/src/main/java/com/teampatch/core/data/di/CoroutineModule.kt
  core/data/src/main/java/com/teampatch/core/data/di/annotation/HarmonyDispatcher.kt
  core/data/src/main/java/com/teampatch/core/data/model/MediaStoreInfo.kt
  core/data/src/main/java/com/teampatch/core/data/repository/local/LocalUserRepositoryImpl.kt
  core/data/src/main/java/com/teampatch/core/data/utils/ContentResolverUtils.kt
Labels: Bug, Feature
