Repository Team-PATCH/Harmony-Android, pull requests merged in 2025-01, with the labels that each got.

#79 BuildType 추가 및 Bottom Navigation ui 추가
  app/build.gradle.kts
  app/src/main/java/com/teampatch/harmony/MainActivity.kt
  app/src/main/java/com/teampatch/harmony/MainNavHost.kt
  app/src/main/java/com/teampatch/harmony/MainViewModel.kt
  build-logic/convention/src/main/java/AndroidLibraryConventionPlugin.kt
  core/data/src/main/java/com/teampatch/core/data/di/DataSingletonModule.kt
  core/data/src/main/java/com/teampatch/core/data/repository/AuthenticationRepositoryImpl.kt
  core/designsystem/src/main/java/com/teampatch/core/designsystem/component/DefaultBottomNavigation.kt
  core/designsystem/src/main/java/com/teampatch/core/designsystem/preview/TodoPreviewParameterProvider.kt
  core/designsystem/src/main/res/drawable/ic_calendar_navigation.xml
  core/designsystem/src/main/res/drawable/ic_home_navigation.xml
  core/designsystem/src/main/res/drawable/ic_question_navigation.xml
  core/designsystem/src/main/res/drawable/ic_store_navigation.xml
  core/domain/src/main/java/com/teampatch/core/domain/fake/FakeFamilyInfo.kt
  core/domain/src/main/java/com/teampatch/core/domain/fake/FakeTodos.kt
  core/domain/src/main/java/com/teampatch/core/domain/model/User.kt
  core/domain/src/main/java/com/teampatch/core/domain/repository/AuthenticationRepository.kt
  core/domain/src/main/java/com/teampatch/core/domain/usecase/authentication/LoginTestAccountUseCase.kt
  core/domain/src/main/java/com/teampatch/core/domain/usecase/family/GetFamilyInfoUseCase.kt
  core/domain/src/main/java/com/teampatch/core/domain/usecase/routine/GetDailyRoutineUseCase.kt
  feature/daily-manage/src/main/java/com/teampatch/daily/manage/DailyManageScreen.kt
  feature/daily-manage/src/main/java/com/teampatch/daily/manage/model/DailyManageUiState.kt
  feature/daily/src/main/java/com/teampatch/harmony/model/DailyUiState.kt
  feature/family-info/src/main/java/com/teampatch/feature/family/info/FamilyInfoNavigation.kt
  feature/family-info/src/main/java/com/teampatch/feature/family/info/FamilyInfoScreen.kt
  feature/family-info/src/main/java/com/teampatch/feature/family/info/FamilyInfoViewModel.kt
  feature/family-info/src/main/java/com/teampatch/feature/family/info/model/FamilyInfoUiState.kt
  feature/home/src/main/java/com/teampatch/feature/home/HomeNavigation.kt
  feature/home/src/main/java/com/teampatch/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/teampatch/feature/home/HomeViewModel.kt
  feature/home/src/main/java/com/teampatch/feature/home/MemberHomeScreen.kt
  feature/home/src/main/java/com/teampatch/feature/home/VipHomeScreen.kt
  feature/profile-edit/src/main/java/com/teampatch/feature/profile/edit/ProfileEditViewModel.kt
  feature/question-detail/src/main/java/com/teampatch/feature/question/detail/QuestionDetailScreen.kt
  feature/question-detail/src/main/java/com/teampatch/feature/question/detail/model/QuestionDetailUiState.kt
  feature/question/src/main/java/com/teampatch/feature/question/QuestionScreen.kt
  feature/question/src/main/java/com/teampatch/feature/question/QuestionScreenNavigation.kt
  feature/question/src/main/java/com/teampatch/feature/question/model/QuestionUiState.kt
Labels: Feature, Setting

#81 질문 화면 연결 및 네트워크 데이터 연결
  app/build.gradle.kts
  app/src/main/java/com/teampatch/harmony/MainActivity.kt
  app/src/main/java/com/teampatch/harmony/MainApp.kt
  app/src/main/java/com/teampatch/harmony/MainNavHost.kt
  app/src/main/java/com/teampatch/harmony/MainViewModel.kt
  core/common/src/main/java/com/teampatch/core/common/PagingDataHelper.kt
  core/data/src/main/java/com/teampatch/core/data/di/DataViewModelModule.kt
  core/data/src/main/java/com/teampatch/core/data/entity/TokenManagerImpl.kt
  core/data/src/main/java/com/teampatch/core/data/mapper/QuestionDetailMapper.kt
  core/data/src/main/java/com/teampatch/core/data/mapper/QuestionMapper.kt
  core/data/src/main/java/com/teampatch/core/data/repository/AnswerRepositoryImpl.kt
  core/data/src/main/java/com/teampatch/core/data/repository/AuthenticationRepositoryImpl.kt
  core/data/src/main/java/com/teampatch/core/data/repository/QuestionRepositoryImpl.kt
  core/designsystem/build.gradle.kts
  core/domain/src/main/java/com/teampatch/core/domain/entity/TokenManager.kt
  core/domain/src/main/java/com/teampatch/core/domain/model/QuestionDetail.kt
  core/domain/src/main/java/com/teampatch/core/domain/repository/AnswerRepository.kt
  core/domain/src/main/java/com/teampatch/core/domain/repository/AuthenticationRepository.kt
  core/domain/src/main/java/com/teampatch/core/domain/repository/QuestionRepository.kt
  core/domain/src/main/java/com/teampatch/core/domain/usecase/answer/AddAnswerUseCase.kt
  core/domain/src/main/java/com/teampatch/core/domain/usecase/answer/EditAnswerUseCase.kt
  core/domain/src/main/java/com/teampatch/core/domain/usecase/authentication/IsLoginRequiredUseCase.kt
  core/domain/src/main/java/com/teampatch/core/domain/usecase/authentication/LoginTestAccountUseCase.kt
  core/domain/src/main/java/com/teampatch/core/domain/usecase/question/AddQuestionCommentUseCase.kt
  core/domain/src/main/java/com/teampatch/core/domain/usecase/question/DeleteQuestionCommentUseCase.kt
  core/domain/src/main/java/com/teampatch/core/domain/usecase/question/EditQuestionCommentUseCase.kt
  core/domain/src/main/java/com/teampatch/core/domain/usecase/question/GetQuestionDetailUseCase.kt
  core/domain/src/main/java/com/teampatch/core/domain/usecase/question/GetQuestionsUseCase.kt
  core/network/build.gradle.kts
  core/network/src/main/java/com/teampatch/core/network/di/NetworkSingletonModule.kt
  core/network/src/main/java/com/teampatch/core/network/interceptor/TokenAuthenticator.kt
  core/network/src/main/java/com/teampatch/core/network/model/question/request/QuestionCardCommentRequestBody.kt
  core/network/src/main/java/com/teampatch/core/network/model/question/response/CommentCreateResponse.kt
  core/network/src/main/java/com/teampatch/core/network/model/question/response/QuestionCardCommentResponse.kt
  feature/answer/src/main/java/com/teampatch/feature/answer/AnswerNavigation.kt
  feature/answer/src/main/java/com/teampatch/feature/answer/AnswerScreen.kt
  feature/answer/src/main/java/com/teampatch/feature/answer/AnswerViewModel.kt
  feature/question-detail/src/main/java/com/teampatch/feature/question/detail/QuestionDetailNavigation.kt
  feature/question-detail/src/main/java/com/teampatch/feature/question/detail/QuestionDetailScreen.kt
  feature/question-detail/src/main/java/com/teampatch/feature/question/detail/QuestionDetailViewModel.kt
  feature/question-detail/src/main/java/com/teampatch/feature/question/detail/mapper/CommentMapper.kt
  feature/question-detail/src/main/java/com/teampatch/feature/question/detail/mapper/PostMapper.kt
  feature/question-detail/src/main/java/com/teampatch/feature/question/detail/model/Comment.kt
  feature/question-detail/src/main/java/com/teampatch/feature/question/detail/model/CommentEdit.kt
  feature/question-detail/src/main/java/com/teampatch/feature/question/detail/model/CommentEvent.kt
  feature/question-detail/src/main/java/com/teampatch/feature/question/detail/model/Post.kt
  feature/question-detail/src/main/java/com/teampatch/feature/question/detail/model/PostEvent.kt
  feature/question-detail/src/main/java/com/teampatch/feature/question/detail/model/QuestionDetailUiState.kt
  feature/question-expand/src/main/java/com/teampatch/feature/question/expand/QuestionExpandNavigation.kt
  feature/question-expand/src/main/java/com/teampatch/feature/question/expand/QuestionExpandScreen.kt
  feature/question-expand/src/main/java/com/teampatch/feature/question/expand/QuestionExpandViewModel.kt
  feature/question/src/main/java/com/teampatch/feature/question/QuestionViewModel.kt
Labels: Feature, Refactor

#87 group network api 리팩토링
  app/src/main/java/com/teampatch/harmony/MainActivity.kt
  app/src/main/java/com/teampatch/harmony/MainNavHost.kt
  core/data/src/main/java/com/teampatch/core/data/repository/GroupManagementRepositoryImpl.kt
  core/designsystem/src/main/java/com/teampatch/core/designsystem/component/OnboardingAppBar.kt
  core/designsystem/src/main/res/drawable/btn_enter_space.xml
  core/domain/src/main/java/com/teampatch/core/domain/repository/GroupManagementRepository.kt
  core/domain/src/main/java/com/teampatch/core/domain/usecase/user/GetUserInfoUseCase.kt
  core/network/src/main/java/com/teampatch/core/network/GroupRemoteDataSource.kt
  core/network/src/main/java/com/teampatch/core/network/model/group/response/GroupInvitationCodeQueryResponse.kt
  core/network/src/main/java/com/teampatch/core/network/model/group/response/GroupInviteRegenerateResponse.kt
  core/network/src/main/java/com/teampatch/core/network/model/group/response/UserGroupListQueryResponse.kt
  feature/onboarding/build.gradle.kts
  feature/onboarding/src/main/AndroidManifest.xml
  feature/onboarding/src/main/java/com/teampatch/feature/onboarding/login/ui/OnboardingEnterScreen.kt
  feature/onboarding/src/main/java/com/teampatch/feature/onboarding/login/ui/OnboardingFirstScreen.kt
  feature/onboarding/src/main/java/com/teampatch/feature/onboarding/login/ui/OnboardingMakeGroupScreen.java
  feature/onboarding/src/main/java/com/teampatch/feature/onboarding/login/ui/OnboardingNavigation.kt
  feature/onboarding/src/main/java/com/teampatch/feature/onboarding/login/ui/OnboardingPermissionNotificationScreen.kt
  feature/onboarding/src/main/java/com/teampatch/feature/onboarding/login/ui/OnboardingRoute.kt
  feature/onboarding/src/main/java/com/teampatch/feature/onboarding/login/ui/OnboardingScreen.kt
  feature/onboarding/src/main/java/com/teampatch/feature/onboarding/login/ui/OnboardingStartScreen.kt
  feature/onboarding/src/main/java/com/teampatch/feature/onboarding/login/ui/OnboardingViewModel.kt
  feature/onboarding/src/main/res/values/strings.xml
Labels: Refactor
